hkshell: "exc for non-existing posts" bug fixed
[bugfix]

Bug's description
-----------------

hkshell.e and other hkshell commands raised an ugly exception when called on a
non-existing post:

    >>> e(11111)
    Traceback (most recent call last):
     File "<console>", line 1, in <module>
     File "/a/cp/hk/hk/hkshell.py", line 621, in inner
       event('after', command, postset=posts)
    UnboundLocalError: local variable 'posts' referenced before assignment

Error
-----

The problem was that the decorator hkshell.postset_operation was not expecting
the `ps` function to raise an exception, which it did, when it got the heapids
of non-existing posts:

    1  try:
    2      command = operation.__name__
    3      event('before', command)
    4      posts = ps(pps)
    5      event('postset_calculated', command, postset=posts)
    6      if len(posts) != 0:
    7          result = operation(posts, *args, **kw)
    8  finally:
    9      event('after', command, postset=posts)

When line 4 failed because `pps` contained non-existing heapids, the `posts`
variable was not set, so line 9 of the finally clause raised another exception
(because it wanted to thead the value of posts`.